name: e2e-ios
on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    env:
      DEVELOPER_DIR: /Applications/Xcode.app

    steps:
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
