name: e2e-ios
on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.0.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check version xcode
        run: xcodebuild -version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'

      - name: Install pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Check version ruby
        run: ruby --version

      - name: Check version cocoapods
        run: pod --version

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd -

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build 

      - name: Detox build
        run: pnpm detox build --configuration ios.release
        env:
          RCT_NO_LAUNCH_PACKAGER: true

      - name: Detox test
        run: pnpm detox test --configuration ios.release --cleanup --headless --record-logs all
