name: e2e-ios
on: push

jobs:
  e2e-ios:
    runs-on: macos-latest
    timeout-minutes: 50

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.0.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check version xcode
        run: xcodebuild -version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'

      - name: Install pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Check version ruby
        run: ruby --version

      - name: Check version cocoapods
        run: pod --version

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd -

      - name: Detox clean cache
        run: pnpm detox clean-framework-cache && pnpm detox build-framework-cache
        env:
          RCT_NO_LAUNCH_PACKAGER: true

      - name: Detox build
        run: pnpm detox build --configuration ios.sim.release
        env:
          RCT_NO_LAUNCH_PACKAGER: true

      - name: Detox test - Inicio de sesión
        run: pnpm detox test --configuration ios.sim.release --headless --record-logs all --testPathPattern=e2e/tests/Flujo\ de\ inicio\ de\ sesión

      - name: Detox test - Resto de pruebas
        run: pnpm detox test --configuration ios.sim.release --headless --record-logs all --testPathIgnorePatterns=e2e/tests/Flujo\ de\ inicio\ de\ sesión --reuse

      # - name: Generar reporte HTML final
      #   run: |
      #     cd e2e/tools/
      #     npm install
      #     node addScreenshotsToReport.js

      # - name: Enviar reporte por correo
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ secrets.SMTP_SERVER }}
      #     server_port: ${{ secrets.SMTP_PORT }}
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: "📱 Reporte Detox iOS E2E"
      #     to: ${{ secrets.EMAIL_TO }}
      #     from: ${{ secrets.EMAIL_USERNAME }}
      #     secure: true
      #     body: |
      #       Hola, se adjuntan los resultados de las pruebas automatizadas
      #       Saludos,
      #       GitHub Actions
      #     attachments: e2e/reports/report.html