name: e2e-ios
on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.0.app

    steps:
      - name: Check version
        run: xcodebuild -version