name: e2e-ios
on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Node
      uses: actions/setup-node@v3

    - name: Install node_modules
      run: |
        npm install

    - name: Pod Install
      run: |
        cd ios && pod install && cd ..

    - name: Install Applesimutils
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Start RN Packager
      run: |
        npx react-native start &

    - name: Build Detox
      run: |
        npx detox build -c ios.release

    - name: Run Detox tests
      run: |
        npx detox test --record-videos all --take-screenshots all -c ios.release

    - name: Upload Test Artifact - GitHub Action
      if: always()
      uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path: artifacts