name: e2e-ios
on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    env:
      DEVELOPER_DIR: /Applications/Xcode.app

    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Check version
        run: xcodebuild -version